/**
 * Insight Model
 */

import { Insight, InsightType, SeverityLevel, Action } from '../types/index';
import { ValidationResult, ValidationError, ValidationWarning } from '../types/index';

export class InsightModel implements Insight {
  insightId: string;
  type: InsightType;
  title: string;
  description: string;
  supportingData: Record<string, unknown>;
  confidence: number;
  impact: SeverityLevel;
  urgency: SeverityLevel;
  recommendedActions: Action[];
  generatedDate: Date;
  generatedBy: string;

  constructor(data: Partial<Insight>) {
    this.insightId = data.insightId || '';
    this.type = data.type || 'data_quality';
    this.title = data.title || '';
    this.description = data.description || '';
    this.supportingData = data.supportingData || {};
    this.confidence = data.confidence ?? 0.5;
    this.impact = data.impact || 'medium';
    this.urgency = data.urgency || 'medium';
    this.recommendedActions = data.recommendedActions || [];
    this.generatedDate = data.generatedDate || new Date();
    this.generatedBy = data.generatedBy || '';
  }

  validate(): ValidationResult {
    const errors: ValidationError[] = [];
    const warnings: ValidationWarning[] = [];

    if (!this.insightId || this.insightId.trim() === '') {
      errors.push({
        field: 'insightId',
        message: 'Insight ID is required',
        code: 'REQUIRED_FIELD',
      });
    }

    const validTypes: InsightType[] = ['data_quality', 'operational', 'clinical', 'predictive'];
    if (!validTypes.includes(this.type)) {
      errors.push({
        field: 'type',
        message: `Type must be one of: ${validTypes.join(', ')}`,
        code: 'INVALID_VALUE',
      });
    }

    if (!this.title || this.title.trim() === '') {
      errors.push({
        field: 'title',
        message: 'Insight title is required',
        code: 'REQUIRED_FIELD',
      });
    }

    if (this.confidence < 0 || this.confidence > 1) {
      errors.push({
        field: 'confidence',
        message: 'Confidence must be between 0 and 1',
        code: 'INVALID_VALUE',
      });
    }

    const validSeverities: SeverityLevel[] = ['critical', 'high', 'medium', 'low'];
    if (!validSeverities.includes(this.impact)) {
      errors.push({
        field: 'impact',
        message: `Impact must be one of: ${validSeverities.join(', ')}`,
        code: 'INVALID_VALUE',
      });
    }

    if (!validSeverities.includes(this.urgency)) {
      errors.push({
        field: 'urgency',
        message: `Urgency must be one of: ${validSeverities.join(', ')}`,
        code: 'INVALID_VALUE',
      });
    }

    if (!this.generatedBy || this.generatedBy.trim() === '') {
      warnings.push({
        field: 'generatedBy',
        message: 'Generated by should be specified',
        code: 'RECOMMENDED_FIELD',
      });
    }

    if (this.recommendedActions.length === 0) {
      warnings.push({
        field: 'recommendedActions',
        message: 'At least one recommended action should be provided',
        code: 'RECOMMENDED_FIELD',
      });
    }

    return {
      isValid: errors.length === 0,
      errors,
      warnings,
    };
  }

  addAction(action: Action): void {
    this.recommendedActions.push(action);
  }

  getPriorityScore(): number {
    const severityScores: Record<SeverityLevel, number> = {
      critical: 4,
      high: 3,
      medium: 2,
      low: 1,
    };

    const impactScore = severityScores[this.impact];
    const urgencyScore = severityScores[this.urgency];
    const confidenceScore = this.confidence * 10;

    return (impactScore + urgencyScore) * confidenceScore;
  }

  toJSON(): Record<string, unknown> {
    return {
      insightId: this.insightId,
      type: this.type,
      title: this.title,
      description: this.description,
      supportingData: this.supportingData,
      confidence: this.confidence,
      impact: this.impact,
      urgency: this.urgency,
      recommendedActions: this.recommendedActions,
      generatedDate: this.generatedDate,
      generatedBy: this.generatedBy,
    };
  }
}
